language: cpp

compiler:
- g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

install:
- mkdir -p ~/gowork/src/github.com/coda-it/
- (cd ~/gowork/src/github.com/coda-it/ && git clone https://github.com/coda-it/cpputillib)

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - g++ --version
  - g++-7 --version
  - make